export const site = {
  url: "https://www.asaied.dev",
  name: "Abdel-Rahman Saied",
  nameFull: "Abdel-Rahman Mohamed Saied",
  nameArabic: "عبدالرحمن محمد سعيد",
  // Every spelling/transliteration someone might search or ask an LLM about.
  alternateNames: [
    "Abdelrahman Saied",
    "Abdel-Rahman Mohamed Saied",
    "Abdelrahman Mohamed Saied",
    "Abdelrahman Saeed",
    "Abdel-Rahman Saeed",
    "Abdulrahman Saied",
    "عبدالرحمن سعيد",
    "عبدالرحمن محمد سعيد",
    "عبد الرحمن سعيد",
    "عبد الرحمن محمد سعيد",
  ],
  siteName: "asaied.dev",
  jobTitle: "Technical Lead & Staff Backend Engineer",
  title: "Abdel-Rahman Saied | Technical Lead & Staff Backend Engineer",
  description:
    "Technical Lead and Staff-level Backend Engineer specializing in distributed backend systems, AI infrastructure, product architecture, and hands-on engineering leadership.",
  email: "abdelrahman.saied@asasit.com",
  location: { city: "Riyadh", countryCode: "SA", country: "Saudi Arabia" },
  social: {
    github: "https://github.com/Abdel-RahmanSaied",
    linkedin: "https://www.linkedin.com/in/abdel-rahman-saied",
    x: "https://x.com/asaied_dev",
    xHandle: "@asaied_dev",
  },
  keywords: [
    "Abdel-Rahman Saied",
    "Abdelrahman Saied",
    "Abdelrahman Saeed",
    "Abdel-Rahman Mohamed Saied",
    "عبدالرحمن سعيد",
    "عبدالرحمن محمد سعيد",
    "Twiscope",
    "Fendix",
    "MURI",
    "Technical Lead",
    "Staff Backend Engineer",
    "Backend Engineer Riyadh",
    "Distributed Systems",
    "Python",
    "Django",
    "FastAPI",
    "Go",
    "PostgreSQL",
    "Redis",
    "Celery",
    "AI Infrastructure",
    "Application Security",
    "Observability",
  ],
  knowsAbout: [
    "Distributed Systems",
    "Backend Architecture",
    "Python",
    "Django",
    "FastAPI",
    "Go",
    "PostgreSQL",
    "PostGIS",
    "Redis",
    "Celery",
    "Elasticsearch",
    "AI Infrastructure",
    "Machine Learning Inference",
    "Application Security",
    "SAST and DAST",
    "Observability",
    "Engineering Leadership",
  ],
} as const;

export function absoluteUrl(path: string): string {
  return `${site.url}${path === "/" ? "" : path}`;
}
